# Pandas
데이터 처리를 위한 라이브러리
* 저수준 API가 대부분인 Numpy는 데이터 핸드링을 하기 어렵다.
* Pandas는 데이터를 DataFrame으로 변경해 데이터 가공/분석을 편리하게 한다.
     * `DataFrame` : 여러 개의 행과 열로 이루어진 2차원 데이터를 담는 데이터 구조체
         * column이 여러 개인 구조체 -> DataFrame = 여러 개의 Series
         * 2차원 데이터는 가장 이해하기 쉽고 효과적으로 데이터를 가공/처리할 수 있다.
     * `Series` : column이 하나인 데이터 구조체
     * `Index` : 개별 데이터를 고유하게 식별하는 key값

## 1. Pandas 시작 - 파일을 DataFrame으로 로딩, 기본 API
Pandas는 다양한 포맷으로 된 파일을 DataFrame으로 로딩할 수 있는 API를 제공한다.
* `read_csv()` : CSV(column을 `,`로 구분)을 변환하는 API
    * `sep` : default값은 `,`이며, 필드구분 문자를 말한다. (`read_csv(sep='\t'` == `read_table()`)
    * `filepath` : 로드하려는 데이터 파일의 경로를 포함한 파일명
* `read_table()` : `tab`으로 필드가 구분된 데이터를 변환하는 API
* `read_fwf()` : 고정 길이 기반의 column 포맷을 변환하는 API

In [2]:
import pandas as pd

titanic_df = pd.read_csv('train.csv')
print('titanic 변수 type : ', type(titanic_df))

titanic 변수 type :  <class 'pandas.core.frame.DataFrame'>


### 1.1. `pd.read_csv()`
* `pd.read_csv()`로 변환 시 첫번 째 줄에 있던 column 문자열이 DataFrame의 column이 된다. 
* 따로 매개변수 값을 할당하지 않으면 csv파일의 첫 번째 row를 DataFrame의 첫 번째 column으로 변환한다.   
* DataFrame의 가장 왼쪽에 있는 숫자는 Index며, DataFrame 내의 모든 데이터는 생성시 고유 키인 Index값을 가지게 된다.

### 1.2. `DataFrame.head()`
일부 데이터만 나타내고 싶을 때는 `DataFrame.head()`를 호출하여 맨 앞의 N개의 row만 반환한다.

In [3]:
titanic_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### 1.3. `DataFrame.shape`
DataFrame의 행과 열의 크기를 알 수 있으며, 행과 열을 튜플 타입으로 반환한다.

In [4]:
print('DataFrame 크기 : ', titanic_df.shape)

DataFrame 크기 :  (891, 12)


### 1.4. `info()`와 `describe()`
#### 1.4.1. `info()`
* 총 데이터 건수와 데이터 타입
* Null 건수 (non-null건수와 총 데이터 건수를 통해 계산)

In [5]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


#### 1.4.2. `describe()`
* column별 숫자형 데이터 값의 n-percentile 분포도
* 평균값, 최대값, 최소값
* 대략적인 분포도를 알 수 있다.
* 해당 숫자 column이 숫자형 카테고리 column(특정 범주에 속하는 값을 코드화한 column)인지 판단할 수 있다.

In [6]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

### 1.5. `value_counts()`
DataFrame의 `[]`에 특정 column명을 입력하면 Series 타입의 특정 column 데이터 세트가 반환이 된다. 이 때 `value_counts()`를 호출하면 각각의 value값과 그에 해당하는 것들의 수를 가장 많은 것 순서대로 정렬하여 반환한다. 

In [7]:
titanic_pclass = titanic_df['Pclass']     # Pclass를 Series 타입으로 반환
print(type(titanic_pclass))

value_cnts = titanic_df['Pclass'].value_counts()
print(value_cnts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


Series는 <strong>Index와 단 하나의 column</strong>으로 구성된 데이터 세트이다.    
이 때 가장 왼쪽에 0부터 시작하는 column이 <strong>Index</strong>이며, 그 옆의 column이 <strong>데이터값</strong>이다.

In [8]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

`value_counts()`는 Series에 정의되어 있으며, 반환 타입이 Series 객체이다.
* column 데이터 값 별 데이터 개수를 반환하므로 고유 column 값을 식별하는 기준으로 사용할 수 있다.
* Index는 DataFrame과 Series가 만들어진 후에도 변경이 가능하다.
* 모든 Index는 고유성이 보장되어야 한다.

In [10]:
value_cnts = titanic_df['Pclass'].value_counts()
print(type(value_cnts))
print(value_cnts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


## 2. DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환
DataFrame은 파이썬의 리스트, 딕셔너리 그리고 Numpy의 ndarray 등과 상호 변환이 가능하다. 특히 Scikitlearn의 많은 API는 DataFrame을 인자로 입력받을 수 있지만, 기본적으로 Numpy의 ndarray를 입력 인자로 사용하는 경우가 대부분이다. 그러므로 그러한 상호변환이 많이 발생한다.

### 2.1. Numpy의 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기
DataFrame은 다음과 같은 특징을 갖고 있다.
* column명을 가지고 있어 다른 데이터 타입보다 편하게 데이터 핸들링이 가능하다.
    * 이 때 column명을 지정해주지 않으면 자동으로 column명을 할당한다.
* data='리스트, 딕셔너리, ndarray', columns='column명 리스트'
* 행과 열을 가지는 2차원 데이터 이므로 <strong>2차원 이하의 데이터들</strong>만 변환할 수 있다.
    * 열의 개수 == col명의 개수
    * col명 리스트는 무조건 1개이다.

In [13]:
import numpy as np

col_name1 = ['col1']     # column명 지정 -> 1차원 즉, col이 1개이므로 col명도 1개 필요
list1 = [1, 2, 3]        # data값
arr1 = np.array(list1)
print('arr1 shape : ', arr1.shape)

# 리스트를 이용해 DataFrame을 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame : \n', df_list1)

# Numpy의 ndarray를 이용해 DataFrame 생성
df_arr1 = pd.DataFrame(arr1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame : \n', df_arr1)

arr1 shape :  (3,)
1차원 리스트로 만든 DataFrame : 
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame : 
    col1
0     1
1     2
2     3


In [14]:
# 3개의 col명이 필요
col_name2 = ['col1', 'col2', 'col3']

# 2행*3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2 = [[1, 2, 3],
         [11, 12, 13]]
arr2 = np.array(list2)
print('array2 shape : ', arr2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame : \n', df_list2)

df_arr2 = pd.DataFrame(arr2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame : \n', df_arr2)

array2 shape :  (2, 3)
2차원 리스트로 만든 DataFrame : 
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame : 
    col1  col2  col3
0     1     2     3
1    11    12    13


딕셔너리를 DataFrame으로 변환 시 딕셔너리의 key값이 column명으로, value값이 column 데이터로 변환된다.

In [15]:
# key는 문자열 column명으로 매핑, value는 리스트 형(또는 dnarray) column 데이터로 매핑
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame : \n', df_dict)

딕셔너리로 만든 DataFrame : 
    col1  col2  col3
0     1     2     3
1    11    22    33


### 2.2. DataFrame을 Numpy의 ndarray, 리스트, 딕셔너리로 변환하기
데이터 핸들링 시 DataFrame으로 변환을 하여 처리를 하고 머신러닝 패키지 입력 인자로 넣기 위해 Numpy의 ndarray로 변환을 하는 경우가 많다.

In [18]:
# DataFrame을 ndarray로 변환
arr3 = df_dict.values      # data값을 ndarray 타입으로 반환
print('df_dict.values 타입 : ', type(arr3), ', df_dict.values shape : ', arr3.shape)
print(arr3)

df_dict.values 타입 :  <class 'numpy.ndarray'> , df_dict.values shape :  (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [19]:
# DataFrame을 리스트로 반환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타임 : ', type(list3))
print(list3)

# DataFrame을 딕셔너리로 반환
dict3 = df_dict.to_dict('list')     # 딕셔너리 value값 타입 지정
print('\n df_dict.to_dict() 타입 : ', type(dict3))
print(dict3)

df_dict.values.tolist() 타임 :  <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입 :  <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


## 3. DataFrame의 column 데이터 세트 생성과 수정
`[]` 연산자를 이용해 DataFrame의 column 데이터 세트의 생성과 수정을 할 수 있다.

In [20]:
titanic_df['Age_0'] = 0     # 새로운 column Age_0 추가 및 0으로 초기화
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

기존 column의 Series의 데이터를 이용해 새로운 column Series를 만들 수 있다.

In [21]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_Num'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_Num  
0           2  
1           2  
2           1

DataFrame 내의 기존 column 값도 쉽게 일괄적으로 업데이트할 수 있다.

In [22]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   

   Family_Num  
0           2  
1           2  
2           1

## 4. DataFrame 데이터 삭제
`drop()` 메서드를 사용해 데이터를 삭제할 수 있다.
* `axis` : column 혹은 row를 삭제한다.
    * `axis=1` : column축 방향으로 column을 삭제한다.
    * `axis=0` : row축 방향으로 row를 삭제한다.
* `lables` : 특정 column 혹은 row를 지정한다.
    * `axis=1` : column명을 `labels`에 입력
    * `axis=0` : index를 `labels`에 입력
* `inplace` : 원 DataFrame의 column도 삭제할 건지를 결정한다.
    * 디폴트값은 False이며, 원 DataFrame의 데이터는 삭제하지 않고 삭제된 결과를 반환한다.
    * True일 경우, 원 DataFrame의 데이터를 삭제하고 None을 반환한다.

In [24]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_Num  
0      0         A/5 21171   7.2500   NaN        S      320.0           2  
1      0          PC 17599  71.2833   C85        C      480.0           2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0           1

리스트 형태로 삭제하고자 하는 column명을 `labels`에 입력하면 여러 개의 column을 삭제할 수 있다.

In [25]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_Num'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값 : ', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값 :  None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [26]:
# axis=0으로 row를 삭제
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))
titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


## 4. Index 객체
Pandas의 Index 객체는 DataFrame, Series의 레코드를 고유하게 식별하는 객체이다. DataFrame, Series에서 Index 객체만 추출하려면 `DataFrame.Index`나 `Series.Index` 속성을 통해 가능하다.

In [27]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('train.csv')

# Index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 array로 반환
print('Index 객체 array값 : \n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값 : 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 2

Index 객체는 1차원 array형태로 데이터를 가지고 있다. 또한 단일값 반환 및 슬라이싱도 가능하다.

In [29]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


하지만 한 번 만들어진 DataFrame 및 Series의 Index 객체는 변경할 수 없다.

In [30]:
indexes[0] = 5

TypeError: Index does not support mutable operations

Series 객체에 연산 함수(max, min, sum 등)를 적용시 Index는 연산에서 제외된다. Index는 오직 <strong>식별용</strong>으로만 사용된다.

In [32]:
series_fair = titanic_df['Fare']
print('Fair Series max값 : ', series_fair.max())
print('Fair Series sum값 : ', series_fair.sum())
print('sum() Fair Series : ', sum(series_fair))
print('Fair Series + 3 : \n', (series_fair+3).head(3))

Fair Series max값 :  512.3292
Fair Series sum값 :  28693.9493
sum() Fair Series :  28693.949299999967
Fair Series + 3 : 
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


`reset_index()`메서드를 사용하면 새롭게 인덱스를 연속적인 숫자로 할당한다. 이 때 기존의 Index는 <strong>index</strong>라는 새로운 column으로 추가가 된다.    
주로 인덱스가 연속된 int 숫자형 데이터가 아닐 경우 주로 사용한다.

In [33]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [34]:
print('#### before reset_index ####')
value_cnts = titanic_df['Pclass'].value_counts()
print(value_cnts)
print('value_cnts 객체 변수 타입 : ', type(value_cnts))

new_value_cnts = value_cnts.reset_index(inplace=False)
print('#### after reset_index ####')
print(new_value_cnts)
print('new_value_cnts 객체 변수 타입 : ', type(new_value_cnts))


#### before reset_index ####
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_cnts 객체 변수 타입 :  <class 'pandas.core.series.Series'>
#### after reset_index ####
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_cnts 객체 변수 타입 :  <class 'pandas.core.frame.DataFrame'>


이 때 `drop=True`로 설정하면 기존 인덱스는 새로운 column에 추가되지 않고 삭제된다.

## 5. 데이터 셀렉션 및 필터링
